"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const file_1 = require("./api/file/file");
const macro_1 = require("./api/macro/macro");
const stack_1 = require("./api/stack/stack");
const boilerplate_1 = require("./boilerplate");
exports.Boilerplate = boilerplate_1.Boilerplate;
const api_1 = require("./api");
exports.API = api_1.API;
const prompt_1 = require("./api/prompt/prompt");
const exec_1 = require("./api/exec/exec");
const template_1 = require("./api/template/template");
api_1.API.Resolver.register('file', file_1.FileAPI);
api_1.API.Resolver.register('macro', macro_1.MacroAPI);
api_1.API.Resolver.register('stack', stack_1.StackAPI);
api_1.API.Resolver.register('prompt', prompt_1.PromptAPI);
api_1.API.Resolver.register('exec', exec_1.ExecAPI);
api_1.API.Resolver.register('template', template_1.TemplateAPI);
